#!/bin/bash
rm -rf dep
virtualenv dep
source dep/bin/activate
easy_install twisted
easy_install txredisapi
easy_install pyyaml
easy_install docopt
easy_install nose
easy_install coverage
easy_install mock
if [ ! -f config.yaml ]
  then
    cp config.yaml.example config.yaml
    echo "Installing default configuration, please change this!"
fi

